/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#f9f9ff",
        surface: {
          DEFAULT: "#f9f9ff",
          dim: "#d3daef",
          bright: "#f9f9ff",
          variant: "#dce2f7",
          tint: "#be0037",
          container: {
            DEFAULT: "#e9edff",
            lowest: "#ffffff",
            low: "#f1f3ff",
            high: "#e1e8fd",
            highest: "#dce2f7",
          },
        },
        "on-surface": "#141b2b",
        "on-surface-variant": "#5c3f40",
        "on-background": "#141b2b",
        "inverse-surface": "#293040",
        "inverse-on-surface": "#edf0ff",
        outline: {
          DEFAULT: "#906f70",
          variant: "#e5bdbe",
        },
        primary: {
          DEFAULT: "#e11f26",
          container: "#c4181e",
          fixed: "#ffe0e1",
          "fixed-dim": "#ffb3b6",
        },
        "on-primary": "#ffffff",
        "on-primary-container": "#fffaf9",
        "inverse-primary": "#ffb3b6",
        secondary: {
          DEFAULT: "#1a1a1a",
          container: "#333333",
          fixed: "#fff3cd",
          "fixed-dim": "#fbb034",
        },
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fffbff",
        tertiary: {
          DEFAULT: "#c48a12",
          container: "#fbb034",
          fixed: "#fff3cd",
          "fixed-dim": "#fbb034",
        },
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#1a1a1a",
        error: {
          DEFAULT: "#ba1a1a",
          container: "#ffdad6",
        },
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
        margin: "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2.5rem",
      },
      fontFamily: {
        display: ['"Plus Jakarta Sans"', "sans-serif"],
        headline: ['"Plus Jakarta Sans"', "sans-serif"],
        body: ['"Hanken Grotesk"', "sans-serif"],
        label: ['"Hanken Grotesk"', "sans-serif"],
      },
      fontSize: {
        "display-xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "price-headline": ["20px", { lineHeight: "24px", fontWeight: "800" }],
        "price-strikethrough": ["13px", { lineHeight: "16px", fontWeight: "400" }],
      },
      boxShadow: {
        card: "0 1px 3px 0 rgba(17, 24, 39, 0.05), 0 1px 2px -1px rgba(17, 24, 39, 0.03)",
        hover: "0 10px 20px -5px rgba(225, 29, 72, 0.08), 0 4px 6px -2px rgba(17, 24, 39, 0.04)",
        sticky: "0 20px 25px -5px rgba(17, 24, 39, 0.08), 0 8px 10px -6px rgba(17, 24, 39, 0.04)",
        header: "0 1px 8px rgba(0,0,0,0.04)",
      },
      maxWidth: {
        store: "1440px",
      },
    },
  },
  plugins: [],
};
